language: python
branches:
  except:
    - staging.tmp
python:
  - "3.6"
services:
  - mysql
env:
  - mysql_user=root magic_database=cards
install:
  - travis_retry pip install -r requirements.txt
  # - ./setup_spellfix.sh
script:
  - python run.py tests
  - mypy --ignore-missing-imports .
  - isort --check-only
